### ISSUE TITLE
Meross component becomes unresponsive after losing Internet connection (even if Internet connection is restored)

### ISSUE THREAD

**Issue by Kalma-House** [albertogeniola/meross-homeassistant#53]
HA Version: 105.2
Component: Latest version: 20200223.2
Devices: various msl120, mss425f,mss425e

The meross cloud component becomes completely unresponsive when it loses Internet connection (even if only for a few minutes). Even after the Internet connection is restored the component does not work (the lights become unavailable, the smartplugs are available but they do not work).The only solution is to restart HA.

This is a link to the debug trace, if you are interested:
https://pastebin.com/x5fjenhs

I believe relevant times are:
2020-02-27 02:46:09 (when meross component loses connection);
2020-02-27 02:46:19 (when meross connection seems restored);
2020-02-27 02:46:20 (when meross connection fails again);
2020-02-27 02:46:30 (when meross component is connected again)

It keeps going thru the same cycle for the next 15 minutes, until
2020-02-27 03:01:44 (when it seems to give up)

However, the internet connection has already been restored by that time. I gave the meross component alamost a whole day to see if it would recover. No dice. I had to restart HA.

Let me know if I can be of further assistance.

Regards,
Javier

**Comment by albertogeniola** [comment]
Hi,
I've fixed a particular bug that was probably causing this issue. Could you please try with the latest version of the library?

**Comment by Kalma-House** [comment]
I have just installed the latest version. I'll see how it perfoms in the next few days and I will keep you posted.

Thanks a lot.

**Comment by albertogeniola** [comment]
Hi @Kalma-House ,
I've released a new one, since the previous did not contain an important update that was addressing the internet connection drop issue. Do you mind updating again?

**Comment by Kalma-House** [comment]
Yes, of course.

**Comment by albertogeniola** [comment]
Hi @Kalma-House ,

any news?

**Comment by Kalma-House** [comment]
The issue is still there.

Here is the link to a HA log:
https://pastebin.com/LGcCNnp3

Relevant times are:
2020-03-10 04:20:31: At that time, Internet connection drops. Meross component detects the failed connention and it keeps trying to reconnect.
2020-03-10 04:31:00: Around that time, Internet connection is restored. At that same time however, Meross component stops trying to reconnect and marks switches as not available, and lights do not respond although they are marked as available.

Setup:
HA Version: 106.2
Component: Latest version: 20200308.3
Devices: various msl120, mss425f,mss425e

Let me know if you need anything else.

Regards,
Javier

**Comment by dalamario** [comment]
Hello Alberto, I have the same problem of Javier, every time my provider change my external IP address (every nights) MEROSS integration stop working.
I tried to uninstall the component and delete the integration, then reinstall everything but without success.

HA version 106.5
Meross component: 20200308.3

**Comment by escaflown23** [comment]
I can confirm the same issue when internet is lost. It was behaving like that before for me. I started noticing this after updating to the latest version. It was fine like 3 version ago.

**Comment by rps-repo** [comment]
I can also confirm the same issue.  If internet goes down even for just a few minutes I have to restart HA to get this integration to begin working again.

**Comment by ryanhindinger** [comment]
I am experiencing the same issue.  Anytime there is an internet outage or IP reset the Meross devices no longer listen to HA until HA is restarted.

**Comment by albertogeniola** [comment]
Hi guys,
sorry for the late reply. As you might know I'm based in Italy and here we have this COVID-19 issue that is absorbing the time I can dedicate to this library. 
Anyways, I find difficult to replicate the issue. For this reason, I'll soon release a special upgrade that will add logging capabilities. I'll ask you to use it and provide the logs.

Keep in touch

**Comment by rgutialo** [comment]
Hi, 
Having the same problem here. Any possible solution?.
I remember with previous meross integration (before meross cloud, I mean), everything was fine. I'm trying to find that version without any luck.

**Comment by rps-repo** [comment]
OK, I have set my config up like you outlined.  I will report back next time this happens.

**Comment by dalamario** [comment]
Hi Alberto,

At the following link you can find my latest disconnetion event recorded with home assistant logger. As you can see , at 01:51:09am internet connection is lost and recovered 10 seconds later, but meross addon never recover the readings :
https://pastebin.com/JgMhe9EA

**Comment by rgutialo** [comment]
This is the error I have in my log:

`2020-03-26 11:17:59 ERROR (Thread-87) [custom_components.meross_cloud.common] Connection to MerossCloud failed.
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/common.py", line 174, in __retry_connection
    self._manager.start()
  File "/usr/local/lib/python3.7/site-packages/meross_iot/manager.py", line 54, in start
    self._device_discoverer.start()
  File "/usr/local/lib/python3.7/threading.py", line 848, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
2020-03-26 11:17:59 ERROR (Thread-87) [custom_components.meross_cloud.common] Connection to MerossCloud failed. Rescheduling
2020-03-26 11:17:59 ERROR (SyncWorker_15) [custom_components.meross_cloud.common] A timeout exception occurred while executing function <function PowerSensorWrapper.update at 0x6f9b38a0> `

**Comment by Kalma-House** [comment]
HA Version: 107.7
Component: Latest version: 20200313.2
Devices: various msl120, mss425f,mss425e

Here is the log for the latest internet disconnection event:
https://pastebin.com/EgbE1jKE

The event starts around 2020-04-03 09:04:12. Unfortunately, the homeassistant log stops recording at 2020-04-03 09:09:06. By that time, however, the internet connection had already been restored. Although the log the stopped recording, the rest of Home Assistant continues working as always, except for the Meross component, which does not obey commands.

Notes:
1) The logbook lists the Meross switches as unavailble at 2020-04-03 09:05:02, and shows their state again at 2020-04-03 09:05:23 (apparently being able to communicate with the Meross cloud again).
2) In the log there are plenty of messages similar to the following (in fact, 108 of them in the last week). Don´t know whether it is related to the problem at hand:
2020-04-03 03:48:59 ERROR (Thread-2) [meross.connection] Failed to process message.

Hope it helps.

Regards,
Javier

**Comment by Kalma-House** [comment]
HA Version: 107.7
Component: Latest version: 20200313.2
Devices: various msl120, mss425f,mss425e

As a way to compare, here is the log of another incident where the meross switches went offline but they DID RECOVER and continued to operate correcly:
https://pastebin.com/d4EVu25t

In this case, the event happenned around 2020-04-04 07:36:59.

Hope it helps.

Regards,
Javier

**Comment by dalamario** [comment]
I had to implement a workaround in order to reset home assistant everytime my external IP change (it normally correspond to my internet disconnections). "Meross_cloud" right now is not 100% reliable, most of the time when it loss the connection, it never recover. Unforunately it's an integration, not an addon and so I was not able to use "hassio.addon_restart" command but had to use the "homeassistant.restart" command instead:

sensor:
  - platform: dnsip
    name: dnsip

automation:
  - alias: HA restart after IP change
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.dnsip
    action:
      service: homeassistant.restart

The automation check IP external address every 120 seconds and if it change, it will restart home assistant.

**Comment by logicup-dev** [comment]
> Hi,
> Having the same problem here. Any possible solution?.
> I remember with previous meross integration (before meross cloud, I mean), everything was fine. I'm trying to find that version without any luck.

I'm using the version : meross-homeassistant-20191228.2... this problem is not present in this old version

**Comment by Kalma-House** [comment]
Hi Alberto,

I have noticed you have made available a new version of the component (20200404.1), which does not reference the latest version of the low-level library. The latest version of the library (and the one I believe may address this issue) is 0.3.2.22, while the version of the library referenced in the component is 0.3.2.21.

Should I wait to update the component (untilthe newest version of the library is refereneced), or should I update now to test if the issue is fixed?

Regards,
Javier

**Comment by albertogeniola** [comment]
Hi guys, 
I've worked on the low-level library and on a new improved version of the Meross-Homeassistant plugin, which should hopefully fix the disconnection problem. Would you mind testing it and report back if that fixed the problem or not? Latest version is **20200411**.
